spring:
  main:
    # 起動時のバーナー表示OFF バーナーはbanner.txtで設定可能
    show-banner: false

  datasource:
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:hsqldb:file:db/test
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/test
#    schema: SAMPLE
#    username:test
#    password:test
    platform: hsqldb
    # false でschema.sql,data.sqlでのデータ初期化が行われなくなる
    initialize: false
#    max-active: 100
#    max-idle: 20
#    min-idle: 20
#    initial-size: 20

  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create-drop
    database: hsql
    # 標準出力にSQLを表示するならtrue
    show-sql: false

  batch:
    job:
       # mainを実行した際にJobを実行するかどうか
#      names: sendMailJob
#      enabled: true
      enabled: false
#    initializer:
#      enabled: true

  velocity:
    checkTemplateLocation: false

logging:
  file: logs/app.log

java:
  mail:
    from: hoge@example.com
    host: 192.168.1.82
    port: 1025
    username: hoge
    password: hoge
